"""Central configuration — stub. See docs/Data_Contracts.md §10 for threshold defaults."""

# Implementation: Stage 1 — populate all thresholds and paths

REPORTING_THRESHOLD = 10_000
STRUCTURING_MARGIN = 500
STRUCTURING_RATIO_THRESHOLD = 0.5
VELOCITY_SPIKE_THRESHOLD = 200
ANOMALY_THRESHOLD = 0.3
BEHAVIOUR_DEVIATION_THRESHOLD = 150
DEFENSE_PLAUSIBILITY_THRESHOLD = 0.4
HIGH_RISK_THRESHOLD = 0.75
MEDIUM_RISK_THRESHOLD = 0.50
REINVESTIGATION_THRESHOLD = 0.45

BASELINE_WINDOW_DAYS = 90
DEFAULT_QUERY_WINDOW_DAYS = 30
ZSCORE_THRESHOLD = 2.5

OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_MODEL = "llama3.2"

DATASET_PATH = "datasets/"
LOG_FORMAT = "structured"
