"""Tribunal Summary Builder — Projection of Adversarial Review (C.5) and Consensus Deliberation (C.6)."""

from __future__ import annotations

from typing import Any

from tribunal.models.tribunal_verdict import TribunalVerdict


class TribunalSummaryBuilder:
    """Builds Section 7 (Defense Review) and Section 8 (Tribunal Deliberation)."""

    def build_defense_summary(self, case_file: Any) -> dict[str, Any]:
        """Construct Section 7: Defense Review Summary."""
        def_cards: list[dict[str, Any]] = []
        if case_file and hasattr(case_file, "evidence_cards"):
            for card in case_file.evidence_cards:
                if getattr(card, "source_expert", "") == "defense":
                    def_cards.append({
                        "card_id": getattr(card, "card_id", "c_def"),
                        "hypothesis": getattr(card, "hypothesis", ""),
                        "confidence": getattr(card, "confidence", 0.0),
                        "supporting_features": getattr(card, "supporting_features", []),
                        "provenance": getattr(card, "provenance", {}),
                    })

        has_defense = len(def_cards) > 0
        summary_text = (
            f"Adversarial Review Engine generated {len(def_cards)} defense cards challenging prosecution hypotheses."
            if has_defense
            else "No alternative hypotheses generated by Adversarial Review Engine."
        )

        return {
            "has_defense_evidence": has_defense,
            "defense_cards_count": len(def_cards),
            "defense_cards": def_cards,
            "summary_statement": summary_text,
        }

    def build_tribunal_summary(self, verdict: TribunalVerdict | None) -> dict[str, Any]:
        """Construct Section 8: Tribunal Deliberation Summary."""
        if not verdict:
            return {
                "verdict": "INCONCLUSIVE",
                "primary_hypothesis": "N/A",
                "primary_score": 0.0,
                "secondary_hypothesis": None,
                "secondary_score": None,
                "confidence_gap": 0.0,
                "confidence": 0.0,
                "risk_level": "LOW",
                "supporting_experts": [],
                "rejected_hypotheses": [],
                "deliberation_trace": [],
                "reasoning_narrative": "No TribunalVerdict issued.",
            }

        v_cat = getattr(verdict, "verdict", "INCONCLUSIVE")
        prim_hyp = getattr(verdict, "primary_hypothesis", getattr(verdict, "winning_hypothesis", "N/A"))
        prim_score = getattr(verdict, "primary_score", getattr(verdict, "winning_score", 0.0))
        sec_hyp = getattr(verdict, "secondary_hypothesis", getattr(verdict, "runner_up_hypothesis", None))
        sec_score = getattr(verdict, "secondary_score", getattr(verdict, "runner_up_confidence", None))
        gap = getattr(verdict, "confidence_gap", 0.0)
        conf = getattr(verdict, "confidence", 0.0)
        risk = getattr(verdict, "risk_level", "MEDIUM")
        rejected = getattr(verdict, "rejected_hypotheses", [])
        experts = getattr(verdict, "supporting_experts", [])
        trace = getattr(verdict, "deliberation_trace", [])

        narrative = (
            f"The Tribunal determined consensus category '{v_cat}' for primary hypothesis '{prim_hyp}' "
            f"with Net Support Score of {prim_score:.4f} and calibrated confidence of {conf:.4f}."
        )
        if sec_hyp and sec_score is not None:
            gap_str = f"{gap:.4f}" if gap is not None else "N/A"
            narrative += f" Secondary hypothesis '{sec_hyp}' scored {sec_score:.4f} (Confidence Gap Delta: {gap_str})."

        pattern_rejections = [r for r in rejected if isinstance(r, dict) and "does not match target query pattern" in r.get("rejection_reason", "")]
        if pattern_rejections:
            narrative += " Note: Higher-confidence anomalies in other pattern categories were not selected because the investigation objective was specifically aligned to the requested query pattern."

        return {
            "verdict": v_cat,
            "primary_hypothesis": prim_hyp,
            "primary_score": round(prim_score, 4),
            "secondary_hypothesis": sec_hyp,
            "secondary_score": round(sec_score, 4) if sec_score is not None else None,
            "confidence_gap": round(gap, 4),
            "confidence": round(conf, 4),
            "risk_level": risk,
            "supporting_experts": experts,
            "rejected_hypotheses": rejected,
            "deliberation_trace": trace,
            "reasoning_narrative": narrative,
        }
